version: "3"

services:
  vscode:
    image: qfortier/latexdevcontainer-minted:1.0.0
    volumes:
      - ../:/workspace/src
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      # Git config
      - ~/.gitconfig:/home/districter/.gitconfig
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=
      - TEXMFHOME=/workspace/texmf
    entrypoint: zsh -c "while sleep 1000; do :; done"
